### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by notrab** [ChiperSoft/atom-mac-classic#4]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by ChiperSoft** [comment]
I'm not using atom any more, so I don't trust myself to make this change, but if you can submit a PR with it that you know works I'll merge it.

**Comment by burodepeper** [comment]
This issue can be closed.
