### ISSUE TITLE
Deprecated selector in `mac-classic/index.less`

### ISSUE THREAD

**Issue by mv-stripe** [ChiperSoft/atom-mac-classic#9]
In `mac-classic/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host,
atom-text-editor` => `atom-text-editor,
atom-text-editor`

* `:host .gutter,
atom-text-editor .gutter` => `atom-text-editor .gutter,
atom-text-editor .gutter`

* `:host.is-focused .cursor,
atom-text-editor.is-focused .cursor` => `atom-text-editor.is-focused .cursor,
atom-text-editor.is-focused .cursor`

* `:host.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,
:host.is-focused .line.cursor-line,
atom-text-editor.is-focused .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,atom-text-editor.is-focused .line.cursor-line,
atom-text-editor.is-focused .line.cursor-line`

* `:host .indent-guide,
atom-text-editor .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor .indent-guide`

* `:host .invisible-character,
atom-text-editor .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor .invisible-character`

* `atom-text-editor::shadow .selection .region` => `atom-text-editor.editor .selection .region`

* `.comment` => `.syntax--comment`

* `.keyword,
.storage` => `.syntax--keyword,
.syntax--storage`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant` => `.syntax--constant`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.variable.language,
.variable.other` => `.syntax--variable.syntax--language,
.syntax--variable.syntax--other`

* `.string` => `.syntax--string`

* `.constant.character.escape,
.string .source` => `.syntax--constant.syntax--character.syntax--escape,
.syntax--string .syntax--source`

* `.meta.preprocessor` => `.syntax--meta.syntax--preprocessor`

* `.keyword.control.import` => `.syntax--keyword.syntax--control.syntax--import`

* `.entity.name.function,
.support.function.any-method` => `.syntax--entity.syntax--name.syntax--function,
.syntax--support.syntax--function.syntax--any-method`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.storage.type.method` => `.syntax--storage.syntax--type.syntax--method`

* `.meta.section .entity.name.section,
.declaration.section .entity.name.section` => `.syntax--meta.syntax--section .syntax--entity.syntax--name.syntax--section,
.syntax--declaration.syntax--section .syntax--entity.syntax--name.syntax--section`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.class,
.support.type` => `.syntax--support.syntax--class,
.syntax--support.syntax--type`

* `.support.constant` => `.syntax--support.syntax--constant`

* `.support.variable` => `.syntax--support.syntax--variable`

* `.keyword.operator.js` => `.syntax--keyword.syntax--operator.syntax--js`

* `.invalid` => `.syntax--invalid`

* `.invalid.deprecated.trailing-whitespace` => `.syntax--invalid.syntax--deprecated.trailing-whitespace`

* `.meta.tag.preprocessor.xml` => `.syntax--meta.syntax--tag.syntax--preprocessor.syntax--xml`

* `.meta.tag.sgml.doctype,
.meta.tag.sgml.doctype .entity,
.meta.tag.sgml.doctype .string,
.meta.tag.preprocessor.xml,
.meta.tag.preprocessor.xml .entity,
.meta.tag.preprocessor.xml .string` => `.syntax--meta.syntax--tag.syntax--sgml.syntax--doctype,
.syntax--meta.syntax--tag.syntax--sgml.syntax--doctype .syntax--entity,
.syntax--meta.syntax--tag.syntax--sgml.syntax--doctype .syntax--string,
.syntax--meta.syntax--tag.syntax--preprocessor.syntax--xml,
.syntax--meta.syntax--tag.syntax--preprocessor.syntax--xml .syntax--entity,
.syntax--meta.syntax--tag.syntax--preprocessor.syntax--xml .syntax--string`

* `.string.quoted.docinfo.doctype.DTD` => `.syntax--string.syntax--quoted.docinfo.syntax--doctype.DTD`

* `.meta.tag,
.declaration.tag` => `.syntax--meta.syntax--tag,
.syntax--declaration.syntax--tag`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.markup.heading` => `.syntax--markup.syntax--heading`

* `.markup.quote` => `.syntax--markup.syntax--quote`

* `.markup.list` => `.syntax--markup.syntax--list`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by NKjoep** [comment]
please have a look at my pull request --> #10

**Comment by burodepeper** [comment]
I've merged #10 and fixed a single lingering style, and published v0.5.0 just now. Enjoy!
